services:
  mon-devis-sans-oublis-frontend-development:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
